trigger:
- master

variables:
  dockerRegistryServiceConnection: '41a6c3aa-821f-4211-a23c-12871c2aa7e4'
  imageRepository: 'apirecipebook'
  containerRegistry: 'recipebookapi.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

pool:
      vmImage: 'ubuntu-latest'

steps:

- task: DownloadSecureFile@1
  displayName: Download appsettings.json
  name: appsettings
  inputs:
    securefile: 'appsettings.Production.json'

- script: |
    cp $(appsettings.secureFilePath) src/Backend/RecipeBook.API

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      latest
      $(tag)