//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeBook.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipeBook.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ingredient list must have at least one ingredient. .
        /// </summary>
        public static string AT_LEAST_ONE_INGREDIENT {
            get {
                return ResourceManager.GetString("AT_LEAST_ONE_INGREDIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list must have at least one instruction.
        /// </summary>
        public static string AT_LIST_ONE_INSTRUCTION {
            get {
                return ResourceManager.GetString("AT_LIST_ONE_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cooking time not supported in Enum..
        /// </summary>
        public static string COOKING_TIME_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("COOKING_TIME_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of difficulty level not supported in Enum.
        /// </summary>
        public static string DIFFICULTY_LEVEL_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("DIFFICULTY_LEVEL_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Dish Type not supported..
        /// </summary>
        public static string DISH_TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("DISH_TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;re duplicated ingredients in List..
        /// </summary>
        public static string DUPLICATED_INGREDIENTS_IN_LIST {
            get {
                return ResourceManager.GetString("DUPLICATED_INGREDIENTS_IN_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered..
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail and/or password invalid..
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should not be any empty ingredients..
        /// </summary>
        public static string INGREDIENT_EMPTY {
            get {
                return ResourceManager.GetString("INGREDIENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient not following the patterns.
        /// </summary>
        public static string INGREDIENT_NOT_FOLLOWING_PATTERN {
            get {
                return ResourceManager.GetString("INGREDIENT_NOT_FOLLOWING_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction cannot be empty.
        /// </summary>
        public static string INSTRUCTION_EMPTY {
            get {
                return ResourceManager.GetString("INSTRUCTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction exceeds the limit of characters..
        /// </summary>
        public static string INSTRUCTION_EXCEEDS_LIMIT_CHARACTERS {
            get {
                return ResourceManager.GetString("INSTRUCTION_EXCEEDS_LIMIT_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of ingredients. The list must have contain between 1 and 5 ingredients..
        /// </summary>
        public static string INVALID_NUMBER_INGREDIENTS {
            get {
                return ResourceManager.GetString("INVALID_NUMBER_INGREDIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password needs to be than 6 characteres..
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request does not have a Token..
        /// </summary>
        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction must have greater than 0..
        /// </summary>
        public static string NON_NEGATIVE_OR_ZERO_INSTRUCTION_STEP {
            get {
                return ResourceManager.GetString("NON_NEGATIVE_OR_ZERO_INSTRUCTION_STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only images (PNG,JPG,JPEG) are accept..
        /// </summary>
        public static string ONLY_IMAGES_ACCEPTED {
            get {
                return ResourceManager.GetString("ONLY_IMAGES_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is different. .
        /// </summary>
        public static string PASSWORD_DIFFERENT_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD_DIFFERENT_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty and must be longer than 6 characteres..
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe not found.
        /// </summary>
        public static string RECIPE_NOT_FOUND {
            get {
                return ResourceManager.GetString("RECIPE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe title cannot be empty..
        /// </summary>
        public static string RECIPE_TITLE_EMPTY {
            get {
                return ResourceManager.GetString("RECIPE_TITLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be two or more instructions in the same order..
        /// </summary>
        public static string TWO_OR_MORE_INSTRUCTIONS_SAME_ORDER {
            get {
                return ResourceManager.GetString("TWO_OR_MORE_INSTRUCTIONS_SAME_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error unknown.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access this resource.
        /// </summary>
        public static string USER_WITHOUT_PERMISSION_ACCESS_RESOURCE {
            get {
                return ResourceManager.GetString("USER_WITHOUT_PERMISSION_ACCESS_RESOURCE", resourceCulture);
            }
        }
    }
}
